//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjLogin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=xxxxxxxxxx;Initial Catalog=prjFriendShip;User ID=sa;Password=xxxxxx;")]
        public string PCR7FriendshipConnectionString {
            get {
                return ((string)(this["PCR7FriendshipConnectionString"]));
            }
            set {
                this["PCR7FriendshipConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=prjFriendShip;Integrated Security=True;")]
        public string HomePCR7FriendshipConnectionString {
            get {
                return ((string)(this["HomePCR7FriendshipConnectionString"]));
            }
            set {
                this["HomePCR7FriendshipConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=xxxxxxxxxx;Initial Catalog=prjFriendShip;User ID=sa;Password=xxxxxxxx" +
            "xx;Encrypt=True;TrustServerCertificate=True")]
        public string prjFriendShipConnectionString {
            get {
                return ((string)(this["prjFriendShipConnectionString"]));
            }
        }
    }
}
